spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-server
          uri: http://auth-server:8080
          predicates:
            - Path=/login, /oauth2/**

server:
  port: ${PORT}
