spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: auth-server
          uri: http://auth-server:8080
          predicates:
            - Path="/login", "/oauth2/**"
        - id: api-users
          uri: lb://api-users
          predicates:
            - Path="/api-users/api/v1/users/**"
        - id: api-notifications
          uri: lb://api-notifications
          predicates:
            - Path="/api-notifications/api/v1/sends/**"

server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: api-users
        url: /api-users/v3/api-docs
      - name: api-notifications
        url: /api-notifications/v3/api-docs
